# VHACK - Very Hackable AI Chatbot Kit Configuration
# WARNING: This is a deliberately vulnerable agent for educational purposes
# DO NOT use in production environments!

agent:
  name: "Very Hackable AI Chatbot Kit"
  version: "1.0.0-VULNERABLE"
  mode: "vulnerable"  # Enables vulnerable behaviors
  admin_password: "admin123"  # Intentionally weak password
  debug_mode: true
  
# AI Provider Configuration
# Choose: openrouter (default), openai, anthropic, huggingface
ai_provider: "openrouter"

# OpenAI Configuration
openai:
  model: "gpt-4o-mini"
  max_tokens: 2000
  temperature: 0.8

# Anthropic Configuration  
anthropic:
  model: "claude-3-haiku-20240307"
  max_tokens: 2000
  temperature: 0.8

# HuggingFace Configuration
huggingface:
  model: "microsoft/DialoGPT-large"
  max_tokens: 2000
  temperature: 0.8

# OpenRouter Configuration (Default)
# NOTE: If tooling is enabled, ensure the model supports it (e.g., "z-ai/glm-4.5-air:free")
openrouter:
  base_url: "https://openrouter.ai/api/v1"
  model: "z-ai/glm-4.5-air:free"  # Available models can be found on OpenRouter: https://openrouter.ai/models
  max_tokens: 2000
  temperature: 0.8  # Higher temperature for more unpredictable responses
  

# Agent behavior configuration
behavior:
  system_prompt: "You are VHACK, a helpful AI assistant designed for security testing education. Your behavior is controlled by dynamic security levels."
  max_conversation_history: 50
  enable_command_execution: true  # Controlled by security level
  log_all_interactions: true
  
# Security level controls progressive implementation of OWASP-based defenses
# Note: Security levels are now controlled dynamically through the web interface
security_level: "low"  # low, medium, high, impossible