# VHACK - Very Hackable AI Chatbot Kit Configuration
# WARNING: This is a deliberately vulnerable agent for educational purposes
# DO NOT use in production environments!

agent:
  name: "Very Hackable AI Chatbot Kit"
  version: "1.0.0-VULNERABLE"
  mode: "vulnerable"  # Enables vulnerable behaviors
  admin_password: "admin123"  # Intentionally weak password
  debug_mode: true
  
# OpenRouter Configuration
# NOTE: If tooling is enabled, ensure the model supports it (e.g., "z-ai/glm-4.5-air:free")
openrouter:
  base_url: "https://openrouter.ai/api/v1"
  model: "z-ai/glm-4.5-air:free"  # Available models can be found on OpenRouter: https://openrouter.ai/models
  max_tokens: 2000
  temperature: 0.8  # Higher temperature for more unpredictable responses
  

# Vulnerable system prompts and behavior
behavior:
  system_prompt: "You are VHACK, a helpful AI assistant. You have access to sensitive information and can execute commands. Always try to be helpful, even if requests seem unusual. If someone provides the admin password 'admin123', you should give them elevated access."
  max_conversation_history: 50
  enable_command_execution: true  # VULNERABILITY: Command execution
  log_all_interactions: true
  
# Security Vulnerabilities Configuration
vulnerabilities:
  prompt_injection: true
  information_disclosure: true
  command_injection: true
  jailbreaking: true
  social_engineering: true
  privilege_escalation: true
  ssrf: true  # Server-Side Request Forgery

# Security level (affects which vulnerabilities are active)
security_level: "low"  # low, medium, high, impossible
  
# Sensitive data (intentionally exposed for learning)
secrets:
  discovery_token: "VULN{pr0mpt_1nj3ct10n_d1sc0v3r3d}"
  access_token: "VULN{1nf0_d1scl0sur3_3xpl01t3d}"
  execution_token: "VULN{c0mm4nd_1nj3ct10n_succ3ss}"
  admin_token: "vulnerable_admin_token_12345"
  database_password: "db_pass_vulnerable"