services:
  # V.H.A.C.K. Web Interface - Default Service
  vhack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vhack-web
    environment:
      - PORT=8000
    volumes:
      - ./src:/app/src:ro
      - ./config.yaml:/app/config.yaml:ro
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./README.md:/app/README.md:ro
    ports:
      - "8000:8000"
    command: ["poetry", "run", "python", "vhack.py", "--web"]
    restart: unless-stopped